apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server
    path: "/exports/lab2"
