apiVersion: v1
kind: Service
metadata:
  labels:
    name: guestbook-frontend
  name: guestbook-frontend
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 4200
  selector:
    app: guestbook-frontend