apiVersion: v1
kind: Service
metadata:
  labels:
    name: guestbook-backend
  name: guestbook-backend
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
  selector:
    app: guestbook-backend