apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-small
spec:
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 50Mi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: nfs-server
    path: "/exports/lab2-small"