apiVersion: v1
kind: Service
metadata:
  labels:
    name: guestbook-database
  name: guestbook-database
spec:
 
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  selector:
    app: guestbook-database
