apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: guestbook-database
spec:
  serviceName: "guestbook-database"
  replicas: 3
  #  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: guestbook-database
  template:
    metadata:
      labels:
        app: guestbook-database
    spec:
    #  terminationGracePeriodSeconds: 10
      containers:
        - image: mongo
          name: guestbook-database
          ports:
            - name: mongodb
              containerPort: 27017
          env:
          - name: MONGO_INITDB_DATABASE
            value: guestbook
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: guestbook-database-secret
                key: mongodb-username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: guestbook-database-secret
                key: mongodb-password
          command:
          - mongod
          - "--replSet"
          - rs0
          - "--bind_ip_all"
          volumeMounts:
          - name: mongodb-volume
            mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-volume
    spec:
      storageClassName: "nfs-csi"
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: 100Mi

